# Ansible Playbook (Configuration Management)

- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Kubernetes Tools
      apt:
        name: kubectl
        state: present

---
